services:
  db:
    image: mysql
    ports: 
        - "3306:3306"
    environment:
        MYSQL_DATABASE: erp
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: test
    volumes:
        - my-db:/var/lib/mysql

  api:
    build: ./api
    environment:
      - DEBUG=false
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CORS_ORIGIN_WHITELIST=${CORS_ORIGIN_WHITELIST}
      - DB_ENGINE=${DB_ENGINE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      - db

  front:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - exclude:/front/node_modules/

  api-node:
    build: ./api_node
    command: nodemon server.js localhost 9090
    ports:
      - "9090:9090"
    volumes:
      - ./api_node:/api_node
      - /api_node/node_modules


volumes:
  my-db:
  exclude:
  react:
  
