# Generated by Django 5.0.2 on 2024-05-15 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0002_compra_orden_bien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='estado',
            field=models.CharField(choices=[('No Iniciado', 'No Iniciado'), ('En proceso', 'En proceso'), ('Terminado', 'Terminado')], default='No Iniciado', max_length=100),
        ),
        migrations.CreateModel(
            name='KardexProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProduccionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'No iniciado'), ('en_proceso', 'En Proceso'), ('completado', 'Terminado')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_models.producto')),
            ],
        ),
    ]
