# Generated by Django 5.0.2 on 2024-05-15 17:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0003_alter_produccion_estado_kardexproducto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kardexproducto',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='kardexproducto',
            name='produccion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api_models.produccionproducto'),
        ),
    ]
