# Generated by Django 5.0.2 on 2024-05-15 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0004_kardexproducto_created_at_kardexproducto_produccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kardexproducto',
            name='produccion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api_models.produccionproducto', unique=True),
        ),
    ]
