# Generated by Django 5.0.4 on 2024-05-15 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0005_alter_kardexproducto_produccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kardexproducto',
            name='produccion',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_models.produccionproducto'),
        ),
    ]
