# Generated by Django 5.0.4 on 2024-07-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_models', '0006_alter_kardexproducto_produccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='kardexproducto',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
